const specialData = [
    {
        id: '1',
        img1: './card/39.jpg',
        img2: './card/6/jpg',
        img3: './card/25.jpg',
        name: 'trim dress',
        price: '$87.00',
        desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.',
    },
    {
        id: '2',
        img1: './card/3.jpg',
        img2: './card/4.jpg',
        img3: './card/5.jpg',
        name: 'belted dress',
        price: '$111.00',
        desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.',
    },
    {
        id: '3',
        img1: './card/1.jpg',
        img2: './card/2.jpg',
        name: 'fitted dress',
        price: '$104.40',
        desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.',
    },
    {
        id: '4',
        img1: './card/8.jpg',
        img2: './card/7.jpg',
        name: 'belted top',
        price: '$49.00',
        desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.',
    },
    {
        id: '5',
        img1: './card/9.jpg',
        img2: './card/6/jpg',
        img3: './card/25.jpg',
        name: 'waist dress',
        price: '$184.00',
        desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.',
    },
    {
        id: '6',
        img1: './card/11.jpg',
        img2: './card/4.jpg',
        img3: './card/5.jpg',
        name: 'crop top',
        price: '$72.60',
        desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.',
    },
    {
        id: '7',
        img1: './card/13.jpg',
        img2: './card/2.jpg',
        name: 'sleeveless dress',
        price: '$261.00',
        desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.',
    },
    {
        id: '8',
        img1: './card/14.jpg',
        img2: './card/8.jpg',
        name: 'v-neck dress',
        price: '$94.50',
        desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters,It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.',
    },
    
]

export default specialData;